version: '3.8'

services:
  sql-ai-agent:
    build: .
    ports:
      - "8501:8501"
    environment:
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SSLMODE=${DB_SSLMODE}
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=${DB_NAME:-sqlai_demo}
      - POSTGRES_USER=${DB_USER:-sqlai_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-sqlai_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
